robotiq_controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_position_controller:
      type: position_controllers/JointGroupPositionController

gripper_position_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_knuckle_joint
