services:
  ros2-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -lc "sleep infinity"
    container_name: ros2_ur5e_dev
    hostname: ros2-ur5e-dev
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - TERM=xterm-256color
      - COLORTERM=truecolor
      - CLICOLOR=1
      - CLICOLOR_FORCE=1
      - FORCE_COLOR=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - ../ros2_ws/src/ur5e_pick_place_bringup:/root/ros2_ws/src/ur5e_pick_place_bringup:rw
      - ../ros2_ws/src/ur5e_pick_place_interfaces:/root/ros2_ws/src/ur5e_pick_place_interfaces:rw
      - ../ros2_ws/src/ur5e_pick_place_mtc:/root/ros2_ws/src/ur5e_pick_place_mtc:rw
      - ../ros2_ws/src/ur5e_tabletop_perception:/root/ros2_ws/src/ur5e_tabletop_perception:rw
      - ../ros2_ws/src/ur5e_workcell_description:/root/ros2_ws/src/ur5e_workcell_description:rw
      - ../external_logs:/root/.ros/log:rw
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
